### ISSUE TITLE
How Authentication is working?

### ISSUE THREAD

**Issue by rianfloo** [loopstudio/rails-api-boilerplate#616]
Hello :)

I've managed to setup and using your boilerplate. It is very helpful thanks a lot!!

However, I successfully created a user using the route `localhost:3000/api/v1/users` with Postman.
Now, I try to make API calls to some resources using access-token & client provided by the success answer but it returns 401 unauthorized. "Authentication is required to perform this action"

Here is my header sent:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/20277876/163355615-c7480c8f-5201-422c-922c-2fa89ea9bcfa.png">

Here is the routes file 

![image](https://user-images.githubusercontent.com/20277876/163355783-377d1d6f-d967-46c9-a2a8-bb4f1a787d57.png)

Would you mind telling me how to make correct requests?

Thanks a lot :)

**Comment by aperezcristina** [comment]
Hello! You need to send the following headers:
`"access-token": "wwwww",
"token-type":   "Bearer",
"client":       "xxxxx",
"uid":          "zzzzz"`

You might want to check out the devise token auth doc in case theres something that's better for your app, and where the configuration is.
https://devise-token-auth.gitbook.io/devise-token-auth/usage/controller_methods#token-header-format

**Comment by rianfloo** [comment]
Thanks, worked perfectly! 

Do you know why sessions#create raises an error : `Can't verify CSRF token authenticity.`

This is the only route which raises that error. 

Anything else is perfect! :)

**Comment by elestu** [comment]
@rianfloo Ideally you'd send a CSRF token on every form submission to avoid CSRF attacks. In this particular implementation there's a `before_action` filter that checks for this token **unless** your request is of type `json`. To accomplish that you'll have to set the `Accept` header to `application/json`.

**Comment by rianfloo** [comment]
@elestu thanks, this is working nicely. Many thanks for your boilerplate. It saved me a lot of config. 🥇 👍
